# Site settings
title: "Tudor Plugaru"
email: contact@tudor.dev
description: >-
  Go beyond the link in bio. Tell a story.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plugaru.me" # the base hostname & protocol for your site

# Personal Information
author:
  name: "Tudor Plugaru"
  location: "Republic of Moldova"
  avatar: "/assets/images/profile.jpeg"

# Social Media Links
social:
  github: "PlugaruT"
  linkedin: "plugarutudor"
  twitter: "PlugaruTudor"
  bluesky: "tudor.bsky.social"
  # website: "https://plugaru.me/"

# Work Experience
work_experience:
  - period: "Oct 2020 — Now"
    position: "Senior Software Engineer"
    company: "Gorgias"
    company_url: "https://www.gorgias.com/"
    location: "Remote"
    # details_file: "gorgias.md"
  - period: "Nov 2018 — Mar 2020"
    position: "Software Engineer"
    company: "MADE.COM"
    company_url: "https://www.made.com/"
    location: "Remote"
    # details_file: "made.md"
  - period: "May 2018 - Oct 2018"
    position: "Software Engineer"
    company: DAS Solutions
    company_url: "https://www.enabld.tech/"
    location: "Republic of Moldova"
    # details_file: "das.md"
  - period: "Aug 2016 - Mar 2018"
    position: "Software Engineer"
    company: "Spark Research Labs"
    location: "Republic of Moldova"
    # details_file: "spark.md"

# Education
education:
  - period: "2013 — 2017"
    degree: "Bachelor's degree of Systems and Computer Engineering at Technical University of Moldova"
    location: "Republic of Moldova"
    project: "Final Research Project: 'Key Performance Indicators Management System'"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Sass/SCSS configuration
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
